using 'main.bicep'

param resourceGroupName = 'slk-portfolio-rg-eus2'
param staticWebAppName = 'slk-portfolio-swa-eus2'
param appName = 'portfolio'
param env = 'prod'
param swaLocation = 'eastus2'
param sku = 'Free'
param customDomain = 'www.samkey.uk'
param communicationServiceName = 'slk-portfolio-acs-glb'
param emailServiceName = 'slk-portfolio-ecs-glb'
param communicationDataLocation = 'UK'
param contactRecipient = 'samkey726@gmail.com'
